### ISSUE TITLE
two child SAs have same reqid only after DPD loss

### ISSUE THREAD

**Issue by lioyerar** [strongswan/strongswan#1855]
**System (please complete the following information):**
 - OS: Ubuntu-22.04
 - Kernel version (if applicable): 5.15.0-79
 - strongSwan version(s): 5.9.11
 - Tested/confirmed with the latest version: yes

**Describe the bug**
Observe two child SAs that have same reqid leading to a situation where one of the tunnels is sending traffic that belongs to the other tunnel.

**To Reproduce**
1. Configure a IKE SA that has two chid SAs with dpd_action = restart.
2. Check that child SAs are installed. At this step, traffic are going to the right tunnel, reqids of child  SAs are 1 and 2 (see traces below).
3. Set link down on peer and wait until to trigger DPD. At this step, child SAs are destroyed.
4. Set link up on peer, child SAs are installed again, but with the same reqid (in my case 2, see traces below). 
5. One tunnel is taken traffic of other.

**Expected behavior**
Traffic should goes to the right tunnel.

**Logs/Backtraces**
Before DPD:
```
root@dut-vm:~/strongswan-5.9.11# swanctl --list-sas
vpn_mme_132: #1, ESTABLISHED, IKEv2, 794d8008224629e1_i* fc972164fcd53a00_r
  local  '10.125.0.1' @ 10.125.0.1[500]
  remote '10.18.110.1' @ 10.18.110.1[500]
  AES_CBC-256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_4096
  established 697s ago, rekeying in 13350s
  active:  IKE_DPD
  sp_mme2: #1, reqid 1, INSTALLED, TUNNEL, ESP:AES_CBC-256/HMAC_SHA2_256_128
    installed 697s ago, rekeying in 2718s, expires in 3263s
    in  c4ed6c8a,      0 bytes,     0 packets
    out c53f5026,    156 bytes,     3 packets,    89s ago
    local  10.10.11.37/32[sctp]
    remote 10.200.0.2/32[sctp]
  sp_mme1: #2, reqid 2, INSTALLED, TUNNEL, ESP:AES_CBC-256/HMAC_SHA2_256_128/MODP_4096
    installed 697s ago, rekeying in 2655s, expires in 3263s
    in  ca397c43,      0 bytes,     0 packets
    out ca08da7c,    104 bytes,     2 packets,    86s ago
    local  10.10.11.37/32[sctp]
    remote 10.200.10.2/32[sctp]
```

After DPD:
```
vpn_mme_132: #2, ESTABLISHED, IKEv2, f278a2d396e02f98_i* 833b5fcfc5e3e38d_r
  local  '10.125.0.1' @ 10.125.0.1[500]
  remote '10.18.110.1' @ 10.18.110.1[500]
  AES_CBC-256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_4096
  established 5442s ago, rekeying in 8444s
  sp_mme2: #5, reqid 2, INSTALLED, TUNNEL, ESP:AES_CBC-256/HMAC_SHA2_256_128/MODP_4096
    installed 2159s ago, rekeying in 1143s, expires in 1801s
    in  c943f680,      0 bytes,     0 packets
    out cbe7b0a2,      0 bytes,     0 packets
    local  10.10.11.37/32[sctp]
    remote 10.200.0.2/32[sctp]
  sp_mme1: #6, reqid 2, INSTALLED, TUNNEL, ESP:AES_CBC-256/HMAC_SHA2_256_128/MODP_4096
    installed 2107s ago, rekeying in 1251s, expires in 1853s
    in  c511a4f2,      0 bytes,     0 packets
    out c02cfaea,      0 bytes,     0 packets
    local  10.10.11.37/32[sctp]
    remote 10.200.10.2/32[sctp]
```

**Additional context**

After analyzing the code, it appears that the bug was introduced by the commit 4958acc. This bug allows a child SA to reuse a previously released reqid. However, a child SA with a different traffic selector might end up allocating a reqid that is already in use.  Typically, in my situation:
- Initially, the child SAs sp_mme2 and sp_mme1 have reqid values of 1 and 2 respectively before DPD.
- After the DPD, sp_mme2 attempts to establish the same reqid of 1. However, the function 'array_remove' in kernel_interface.c sets it to 2.
- Subsequently, sp_mme1 attempts to establish reqid of 2, which it obtains successfully, but this reqid is already in use by sp_mme2.

I reproduced this behavior only after a DPD loss, because following a DPD loss, the child SA attempts to re-allocate the same reqid used previously. I am uncertain whether this behavior is intended or not.

I have a question regarding the comment that you left in the `alloc_req` function:
 we don't require a traffic selector match for explicit reqids,
 as we want to reuse a reqid for trap-triggered policies that
 got narrowed during negotiation. 
 
Is it necessary? My first intention was to delete this optimization and do a search by traffic selectors directly or reset reqid as inititial config after DPD loss.

**Comment by tobiasbrunner** [comment]
> This bug allows a child SA to reuse a previously released reqid.

Yes, I can see how this can happen (e.g. when a new CHILD_SA is initiated while another is recreated concurrently).

But at first glance it seems weird that it does in your case. Because the order in which the reqids are released should be the same in which they are allocated i.e. the CHILD_SAs are recreated (reqids are added at the end of the array when released and removed from the front when allocated). The reason why that's not the case is because the IKE_SA destroys CHILD_SAs in reverse order for some reason:

https://github.com/strongswan/strongswan/blob/0bff5c98bcfa7cd6855af5f35812872191317489/src/libcharon/sa/ike_sa.c#L3024-L3028

Using `ARRAY_HEAD` here should workaround the issue in your case. But it's definitely not a complete fix.

To avoid the issue altogether, we should probably keep the reqids allocated while recreating CHILD_SAs (e.g. by calling `alloc_reqid()` in `child_create_t::use_reqid()` and in some cases even outside as the CHILD_SA might get destroyed before such a task is created e.g. when handling DELETEs with `close_action`). I'll have to look into that.


> Is it necessary?

I wondered that myself often enough. But there are definitely cases where it is. For instance, with SELinux labels, policies are only installed for the trap policy with generic label. For SAs with specific labels that are created later based on that, no policies are installed but the SAs do need to have the same reqid for them to work. As long as there is no narrowing, this would still work without passing the reqid, but if there is (e.g. if the responder narrows the proposed `0.0.0.0/0` to a list of subnets) it won't.

**Comment by tobiasbrunner** [comment]
> For instance, with SELinux labels, policies are only installed for the trap policy with generic label. For SAs with specific labels that are created later based on that, no policies are installed but the SAs do need to have the same reqid for them to work.

At one point, the per-CPU SAs patches (_per-cpu-sas-poc_ branch) used a similar approach, where only the first (non-CPU-specific) CHILD_SA installed a trap policy that triggers per-CPU acquires (I changed that in the latest iteration of the patches, though).

There is also another scenario that's mentioned in a comment: When traffic matches a trap policy, the kernel creates a temporary SA to avoid triggering multiple acquires. Only if we use the same reqid will the CHILD_SA that's negotiated and then installed replace/remove that. So that wouldn't be the case if there was narrowing and a new reqid got allocated, that is, the non-replaced temporary SA would then prevent further acquires for the same trap policies (i.e. for traffic outside the narrowed policy that still matches the wider trap policy). Leaving that larval SA until it expires (takes close to 3 minutes in the default config) is definitely not ideal (in our test environment it would be treated as an error), but it might not actually be a problem in practice. For instance, for the [trap-any scenario](https://strongswan.org/testing/testresults/ikev2/trap-any/index.html), which uses transport mode, packets to every new peer that match the same trap policy would create a separate acquire and temporary SA, and in tunnel mode scenarios it's relatively rare that multiple acquires for the same trap policy will result in differently narrowed SAs (it can't be ruled out entirely, though).

It's important to note that this particular issue only occurs when the SA is created from an acquire initially, not once it's recreated due to DPD. Similarly, we also don't maintain the reqid anymore if a trapped config is initiated manually (i.e. the resulting SA gets a different reqid than the trap policy if there is narrowing). In either case, however, there could be a temporary SA that's not replaced if acquires are triggered concurrently with reestablishing an SA with narrowed TS (a duplicate SA with the reqid of the trap policy is actively prevented in newer strongSwan versions).

So while we can't get rid of the code in `alloc_reqid()` (we definitely want to maintain the reqid during rekeying, but that happens overlapping so that's generally already handled correctly), we could possibly omit copying the reqid when reestablishing SAs from scratch. But it might still be more stable if we kept the reqid allocated while a CHILD_SA is recreated (that could even be helpful during rekeying if the soft expire is too close to the hard expire).

**Comment by lioyerar** [comment]
Thank you, that's clear and well-explained.

> The reason why that's not the case is because the IKE_SA destroys CHILD_SAs in reverse order for some reason

I confirmed that in my case, the order of destroying child SAs is different from the order of creation by the peer (the dpd_action=restart was in the peer's configuration).

> To avoid the issue altogether, we should probably keep the reqids allocated while recreating CHILD_SAs (e.g. by calling alloc_reqid() in child_create_t::use_reqid()

I'm not sure I fully understand your solution. Do we have the guarantee of the order of destruction and recreation of child SAs? Instead of relying on array_remove, which might not guarantee the desired order, should we consider array_bsearch despite the potential time complexity?

**Comment by tobiasbrunner** [comment]
> Do we have the guarantee of the order of destruction and recreation of child SAs?

I already told you how to reverse the order to avoid the issue in your case.

My suggestion is to not release the reqid when the old CHILD_SA is destroyed while a new one is getting established concurrently.

**Comment by lioyerar** [comment]
Hello,

Sorry, I  misunderstanding your comment. I have reversed the order when IKE_SA destroys CHILD_SAs and it actually fix my case.

I have also discovered an another case to reproduce with static reqid:
- configre one CHILD_SA with static reqid `reqid = 1`
- initiate first a CHILD_SA with dynamic allocated reqid,  it should established a tunnel with reqid = 1
- then initiate the statically configured reqid, the established tunnel has also reqid = 1  

```
root@dut-vm:~# swanctl --initiate --child sp_mme1                                                                                                                                                         
...                                                                                       
initiate completed successfully                                                                                             
root@dut-vm:~# swanctl --initiate --child sp_mme2 (static reqid)
...
                                                                                                                                                    
root@dut-vm:~# swanctl --list-sas                                                                                           
vpn_mme_132: #1, ESTABLISHED, IKEv2, 94cd98efd216fcc0_i* ee28efdcda99ef01_r                                                 
  local  '10.125.0.1' @ 10.125.0.1[500]                                                                                     
  remote '10.18.110.1' @ 10.18.110.1[500]                                                                                   
  AES_CBC-256/HMAC_SHA2_256_128/PRF_HMAC_SHA2_256/MODP_4096                                                                 
  established 6s ago, rekeying in 13989s                                                                                    
  sp_mme1: #1, reqid 1, INSTALLED, TUNNEL, ESP:AES_CBC-256/HMAC_SHA2_256_128                                                
    installed 6s ago, rekeying in 3252s, expires in 3954s                                                                   
    in  c2286126,      0 bytes,     0 packets                                                                               
    out c27bafd6,      0 bytes,     0 packets                                                                               
    local  10.10.11.37/32[sctp]                                                                                             
    remote 10.200.10.2/32[sctp]                                                                                             
  sp_mme2: #2, reqid 1, INSTALLED, TUNNEL, ESP:AES_CBC-256/HMAC_SHA2_256_128/MODP_4096                                      
    installed 5s ago, rekeying in 3263s, expires in 3955s                                                                   
    in  c31af553,      0 bytes,     0 packets                                                                               
    out cbbec0c9,      0 bytes,     0 packets                                                                               
    local  10.10.11.37/32[sctp]                                                                                             
    remote 10.200.0.2/32[sctp]                                                                                              
```

So even by calling `alloc_reqid` in `child_create_t::use_reqid()`, it should still exist.
By the way, I have a question regarding this part:
> in some cases even outside as the CHILD_SA might get destroyed before such a task is created e.g. when handling DELETEs with close_action) 

If the CHILD_SA gets destroyed before the recreate task, what is the problem behind that? If the CHILD_SA is already destroyed, won't `alloc_reqid` create a new entry from the traffic selector, right?
I wonder if the CHILD_SA will get a different reqid, but at least we won't have a CHILD_SA taking an in-use reqid (with the workaround patch applied)? I do not have the setup to reproduce this, it is not evident

Lastly, is the workaround upstream-able?

**Comment by tobiasbrunner** [comment]
> I have reversed the order when IKE_SA destroys CHILD_SAs and it actually fix my case.

Yes, that's what I expected.

> I have also discovered an another case to reproduce with static reqid:
> 
>    * configre one CHILD_SA with static reqid `reqid = 1`
>    * initiate first a CHILD_SA with dynamic allocated reqid,  it should established a tunnel with reqid = 1
>    * then initiate the statically configured reqid, the established tunnel has also reqid = 1

That's a misconfiguration. If you want to mix static reqids and dynamic reqids increase `charon.reqid_base` to a value above your static reqids.

> If the CHILD_SA gets destroyed before the recreate task, what is the problem behind that? If the CHILD_SA is already destroyed, won't alloc_reqid create a new entry from the traffic selector, right?

No, the `alloc_reqid()` call will receive the reqid of the destroyed SA, so if another CHILD_SA was created in the meantime it might got that reqid reallocated. That results in the same issue you saw.

> I wonder if the CHILD_SA will get a different reqid, but at least we won't have a CHILD_SA taking an in-use reqid (with the workaround patch applied)?

No, the workaround has no effect on that as the SAs are destroyed via a different code path when the peer sends a DELETE.

> Lastly, is the workaround upstream-able?

Yes, I will push a fix for that and try to come up with a solution for the other race conditions (probably later this week, but not sure yet as I have to prepare for a conference next week).

**Comment by lioyerar** [comment]
> Yes, I will push a fix for that and try to come up with a solution for the other race conditions (probably later this week, but not sure yet as I have to prepare for a conference next week).

Hello, may I kindly ask if there are any updates?

**Comment by tobiasbrunner** [comment]
The workaround is now in master. A solution for the other possible races will take some more time as the reqid allocation is kinda weird.

**Comment by tobiasbrunner** [comment]
I've pushed a bunch of commits to the _1855-reqid-refcount_ branch that aim to maintain the reqid of a CHILD_SA correctly when recreating it (whether from scratch or during rekeying) or when handling an acquire for a trap policy with a particular reqid if that was dynamically allocated.

The idea is to increase the reference counter for a particular reqid while a CHILD_SA with that reqid is (re-)created so it doesn't get re-allocated to a different CHILD_SA if the old CHILD_SA is destroyed or the trap policy is uninstalled before the new CHILD_SA is installed.
