### ISSUE TITLE
proposal_keywords.c is excluded by the .gitignore file

### ISSUE THREAD

**Issue by WardLindekens** [strongswan/strongswan#2214]
**System (please complete the following information):**
 - OS: 
 - Kernel version (if applicable): 
 - strongSwan version(s): [e.g. 5.9.14]
 - Tested/confirmed with the latest version: [**yes**/no]

**Describe the bug**
When adding a new version upstep to gitlab the proposal_keywords.c does not get added as it is matched by the following line in the gitignore:
https://github.com/strongswan/strongswan/blob/5.9.14/.gitignore#L29

**To Reproduce**
1. Have a git repo where the source code (downloaded from https://download.strongswan.org/) is added
2. git add -a
3. strongswan-5.9.14/src/libstrongswan/crypto/proposal/propsal_keywords.c does not get added to the git repo.

**Expected behavior**
This file should be present for strongswan to compile correctly. It can be forced, but might be overlooked easily.

**Additional context**
.gitignore file should possibly be changed to only ignore the other keywords.c files.

**Comment by tobiasbrunner** [comment]
Thanks for the report.

There are no `.gitignore` files contained in the tarballs. So did add that one (and maybe others) yourself? Also, did you consider using `git submodule` instead of importing tarballs?

I guess we could maybe explicitly not ignore the file with `!proposal_keywords.c`, but since we already have it in our repository that would really only be for this very specific use case.
