### ISSUE TITLE
libstrongswan/utils/utils/memory.h:50:20: error: 'memcpy' offset [0, 3] is out of the bounds [0, 0] [-Werror=array-bounds=]

### ISSUE THREAD

**Issue by dilyanpalauzov** [strongswan/strongswan#2509]
Compiling with gcc 14.2.1 with -flto -O3 fails on master branch 0be6fd773 with:
```
  CCLD     libstrongswan.la 
In function 'memcpy_noop',
            inlined from 'get_subset' at ../../../src/libstrongswan/selectors/traffic_selector.c:431:2,
            inlined from 'get_subset' at ../../../src/libstrongswan/selectors/traffic_selector.c:358:1,
            inlined from 'is_contained_in' at ../../../src/libstrongswan/selectors/traffic_selector.c:550:40:
../../../src/libstrongswan/utils/utils/memory.h:50:20: error: 'memcpy' writing between 4 and 16 bytes into a region of size 0 overflows the destination [-Werror=stringopoverflow=]
50 |         return n ? memcpy(dst, src, n) : dst; 
   |                    ^                                                          
In function 'is_contained_in':
lto1: note: destination object is likely at address zero
```
Without -flto the same happens

**Comment by tobiasbrunner** [comment]
Thanks for the report. While I can reproduce this warning/error, it looks like a compiler bug to me.

I don't see why an array with a fixed size of 16 (see [here](https://github.com/strongswan/strongswan/blob/0be6fd7735847a71b307b908fd71e972b3ad0852/src/libstrongswan/selectors/traffic_selector.c#L78)) would suddenly have zero length there due to some kind of optimization.

And if it is because `subset` could theoretically be `NULL`, it's weird that this particular case

https://github.com/strongswan/strongswan/blob/0be6fd7735847a71b307b908fd71e972b3ad0852/src/libstrongswan/selectors/traffic_selector.c#L430-L433

would be so special. See e.g. the almost identical code in `clone()`:

https://github.com/strongswan/strongswan/blob/0be6fd7735847a71b307b908fd71e972b3ad0852/src/libstrongswan/selectors/traffic_selector.c#L636-L642

Maybe with `-O3`, the compiler reuses the last lines of `traffic_selector_create_from_bytes()`:

https://github.com/strongswan/strongswan/blob/0be6fd7735847a71b307b908fd71e972b3ad0852/src/libstrongswan/selectors/traffic_selector.c#L739-L741

and because those follow  a `NULL` check

https://github.com/strongswan/strongswan/blob/0be6fd7735847a71b307b908fd71e972b3ad0852/src/libstrongswan/selectors/traffic_selector.c#L727-L733

it does something weird here (that function is called with uncontrolled `type` argument, though, so the constructor could fail, which isn't the case in `get_subset()`).

Besides a `NULL` check, adding a useless `subset->netbits = this->netbits;` before the first `memcpy()` also removes the warning for some reason (again indicating that this warning is bogus). Another way to remove it seems to be to replace `size` with e.g. `sizeof(this->from)`. I guess I'll go with the latter as a workaround (see the `2509-ts-gcc-warning` branch).
