### ISSUE TITLE
Test failures in musl systems

### ISSUE THREAD

**Issue by icp1994** [strongswan/strongswan#2557]
**System (please complete the following information):**
 - OS: Void Linux 
 - strongSwan version(s): 6.0.0

**Describe the bug**
A couple of tests from `traffic selector` suite fail in a musl system
``` 
Running suite 'traffic selector':
    Running case 'create': -+++++++++++++++++++++
      Failure in 'test_create_from_string': 10.1.0.0/16[tcp/80] != 10.1.0.0/16[tcp/http] or 10.1.0.0/16[6/80] (suites/test_traffic_selector.c:36, i = 0)
    Running case 'addresses': ++
    Running case 'to_subnet': +++++++++++++++++++
    Running case 'subset': ++-++++++
      Failure in 'test_subset_equal': 10.1.0.0/16[tcp/80] != 10.1.0.0/16[tcp/http] or 10.1.0.0/16[6/80] (suites/test_traffic_selector.c:36, i = 0)
    Running case 'includes': ++++++++++
    Running case 'is_contained_in': +++++++
    Running case 'is_host': ++++++++++++++++++
    Running case 'set_address': +++++++++
    Running case 'cmp': ++++++++++++++++++++
    Running case 'clone': +
    Running case 'hash': +
    Running case 'icmp': ++++++++++
    Running case 'printf hook': ++
  Passed 11/13 'traffic selector' test cases
```
**Additional context**
The full build log is [also available](https://productionresultssa10.blob.core.windows.net/actions-results/fa9ed914-9da9-4811-b9a9-4b24fe0aec86/workflow-job-run-593b5b6d-e7e6-5f1d-3be6-43ead66e4d56/logs/job/job-logs.txt?rsct=text%2Fplain&se=2024-12-04T15%3A14%3A51Z&sig=WBLSnWRFjqlz0equmHtOgeRsH4OiNG0I7bT%2F%2FfLOlBw%3D&ske=2024-12-05T01%3A35%3A41Z&skoid=ca7593d4-ee42-46cd-af88-8b886a2f84eb&sks=b&skt=2024-12-04T13%3A35%3A41Z&sktid=398a6654-997b-47e9-b12b-9515b896b4de&skv=2024-11-04&sp=r&spr=https&sr=b&st=2024-12-04T15%3A04%3A46Z&sv=2024-11-04) if that's of any help.

**Comment by tobiasbrunner** [comment]
You system seems to lack entries for `getprotobyname()` and/or `getservbyname()` (`/etc/protocols` and/or `/etc/services`, respectively).

**Comment by icp1994** [comment]
The iana protocol & service files seems to be present already in the base system. But maybe musl needs a `netdb.h` import somewhere?

**Comment by tobiasbrunner** [comment]
I don't think it's an include problem, otherwise it would not have compiled (also, our [musl-based CI build](https://cirrus-ci.com/task/5381476177412096) runs these tests successfully). These names are evaluated at runtime by the two functions above, which are provided by the C library. Maybe the test process has no access to those files or they are in a different format than expected ([this](https://git.musl-libc.org/cgit/musl/tree/src/network/lookup_serv.c#n73) seems to be the lookup function for the services/ports, the protocols seem to be hard-coded [here](https://git.musl-libc.org/cgit/musl/tree/src/network/proto.c), but `tcp` is in the list, so that should be fine).
