### ISSUE TITLE
Add support for AES in OCB mode

### ISSUE THREAD

**Issue by WRMSRwasTaken** [strongswan/strongswan#587]
**Is your feature request related to a problem? Please describe.**
None at all.

**Describe the solution you'd like**
The patent for OCB ([RFC7253](https://datatracker.ietf.org/doc/html/rfc7253)) has been abandoned a while ago: https://mailarchive.ietf.org/arch/msg/cfrg/qLTveWOdTJcLn4HP3ev-vrj05Vg/
and because of this, I think this would be a great addition for strongSwan as a new mode for AES. According to the internet ([citation needed]...) apparently it's even faster than AES in GCM mode.

**Describe alternatives you've considered**
None needed.

**Additional context**
OpenSSL 3.0.0 has just been released with AES-OCB mode support according to [the changelog](https://www.openssl.org/news/changelog.html#openssl-30):
```
Added support for OCB mode. OpenSSL has been granted a patent license compatible with the OpenSSL license for use of OCB.
Details are available at https://www.openssl.org/source/OCB-patent-grant-OpenSSL.pdf.
Support for OCB can be removed by calling config with no-ocb.
```

€: To be honest, I am not familiar at all with the kernel crypto but I think the kernel needs to support this aswell...

**Comment by tobiasbrunner** [comment]
The use of AES in OCB mode is not standardized for use with IKEv2 or IPsec. There is [a draft from 2001](https://datatracker.ietf.org/doc/html/draft-moskowitz-aes128-ocb), probably abandoned due to the patent at the time. There was [a discussion](https://mailarchive.ietf.org/arch/msg/ipsec/R4JB71uHjhV3Lh2ujawdSpY4bX4/) on the _ipsecme_ working group mailing list earlier this year, with no clear consensus. So far it hasn't been added to the WG charter and there were also no independent draft submissions (I guess the advantages over the widely adopted GCM mode aren't significant enough to gain much traction). So it will probably be a while until anything happens in this regard (if at all).

**Comment by WRMSRwasTaken** [comment]
Yeah okay, fair. I am going to close this and wait to see if something about this topic will come up again in the IKEv2 / IPsec space since this topic is gaining some attention by the TLS people, thanks!
