### ISSUE TITLE
PKI tool generates invalid certificates sometimes

### ISSUE THREAD

**Issue by Alvenix** [strongswan/strongswan#631]
**System:**
 - OS: Ubuntu 20.04
 - Kernel version: 5.10.0-1045-oem
 - strongSwan version: 5.9.2
 - Tested/confirmed with the latest version: no

**Describe the bug**
I use the PKI tool to generate 10,000 certificates. Sometimes the generated certificates are corrupted.

**To Reproduce**
```
#!/bin/bash

# Generate CA Key
pki --gen --size 521 --type ecdsa > ca_key.der
# Generate CA Cert
pki --self --in ca_key.der --dn "CN=ca_root" --ca > ca_cert.der

for i in `seq 1 100000` 
do
        echo $i
        # Generate Cert Key
        pki --gen --size 521 --type ecdsa > key.der
        # Generate Cert
        pki --issue --in key.der --type priv --cacert ca_cert.der --cakey ca_key.der --dn "CN=test" --san test > cert.der
        openssl x509 -inform der -in cert.der -text || { echo 'Invalid certificate' ; exit 1; }
done
```

**Expected behavior**
All generated certificates should be valid.

**Logs/Backtraces**
Relevant openssl decode error:
```
140537539729216:error:0D0E20DD:asn1 encoding routines:c2i_ibuf:illegal padding:../crypto/asn1/a_int.c:187:
140537539729216:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:646:Field=serialNumber, Type=X509_CINF
140537539729216:error:0D08303A:asn1 encoding routines:asn1_template_noexp_d2i:nested asn1 error:../crypto/asn1/tasn_dec.c:646:Field=cert_info, Type=X509
```

**Additional context**
None.

**Comment by tobiasbrunner** [comment]
Thanks for the report. ASN.1 integers are always encoded as positive numbers in two's complement, i.e. if the most significant bit (MSB) of the first byte is set (i.e. it's a negative number), their encoding is prefixed with a zero byte. Here it looks like the randomly allocated serial numbers are sometimes encoded incorrectly, with a zero prefix even though the MSB of the second byte is not set (thus the illegal padding error by OpenSSL).

This happens if the first byte of the allocated 8 byte serial is `0x80` (i.e. only the MSB is set) and if the next byte doesn't have its MSB set. In order to ensure that all serials are positive numbers, `pki --issue` masks the first bit of the generated serial since e49197f15eef80f5559fcb631d4a4c51ae7867e7. However, in this case this results in a 0 byte that looks like a prefix, but actually isn't.

I pushed a fix for this to the _631-pki-serial_ branch.

**Comment by tobiasbrunner** [comment]
> ASN.1 integers are always encoded as positive numbers in two's complement, i.e. if the most significant bit (MSB) of the first byte is set (i.e. it's a negative number), their encoding is prefixed with a zero byte.

That's only true in so far as strongSwan's `asn1_integer()` assumes that all passed numbers are positive and always adds a zero prefix if the MSB of the first byte is set. Therefore, e49197f15eef80f5559fcb631d4a4c51ae7867e7 is not actually necessary to fix a violation of RFC 5280, serials were always encoded correctly as positive integers.

Maybe the patch was triggered by how OpenSSL displays serial numbers in `openssl x509 -text`. A zero prefixed serial number generated by `pki` will only be shown as hex dump:

    Serial Number:
            af:e2:e1:47:0f:66:b5:a4

While serial numbers that don't have the MSB of the first byte set are shown as actual numbers too:

    Serial Number: 289805014144645117 (0x405981ffa37f7fd)

The reason for that is that OpenSSL does the latter only if the serial fits into a signed `long` variable, which isn't the case if the MSB of an 8-byte number is set (even though, `sizeof(long)` is 8 on 64-bit platforms, the value would be interpreted as a negative number, which it explicitly isn't due to the zero prefix). So instead of fixing a violation of RFC 5280, e49197f15eef80f5559fcb631d4a4c51ae7867e7 ensured (or at least attempted to) that all generated serials are positive 64-bit numbers in two's complement, which OpenSSL will print as numbers. I've documented that in the commit message.
