### ISSUE TITLE
macOS 12 Monterey - installing virtual IP failed, no acceptable traffic selectors found

### ISSUE THREAD

**Issue by tzahico** [strongswan/strongswan#707]
Hello,

OS: macOS Monterey 12.0.1
MacBook Air M1 2020, 8GB RAM   (tested also on an Intel device running Monterey)
strongSwan version(s): 5.9.0, Dawrin 21.1.0 x86_64
Tested/confirmed with the latest version: Yes, it was also tested with Strongswan 5.9.4

Strongswan worked well for us on all macOS versions (including Big Sur), but it seems that we get the following error every time that we try to establish an IKEv2-IPSec connection on macOS Monterey:

```
> Created TUN device: utun4
> Created TUN device: utun4
> interface utun4 appeared
> virtual IP 10.110.10.33 did not appear on utun4
> installing virtual IP 101.110.10.33 failed
> selected proposal: EPS:AES_CBC_128/HMAC_SHA1_96/NO_EXT_SEQ
> no acceptable traffic selectors found
> failed to establish CHILD_SA, keeping IKE_SA

```

The issue might be related to the workaround in lines 850 and 870 of https://github.com/strongswan/strongswan/blob/master/src/libcharon/plugins/kernel_pfroute/kernel_pfroute_net.c - perhaps a longer delay would fix it?

Thanks,
Isaac

**Comment by tobiasbrunner** [comment]
Please try increasing `charon.plugins.kernel-pfroute.vip_wait` (the default is 1000ms).

**Comment by tzahico** [comment]
Thank you @tobiasbrunner  for your prompt reply.  

We tried:
1. Changing charon.plugins.kernel-pfroute.vip_wait to 10000
2. Changing usleep on kernel_pfroute_net.c  lines 850 and 870 to 50000

Unfortunately, the result is the same.

Does anyone has success connecting on macOS Monterey?  or this issue is specific for our config?

Thanks,
Isaac

**Comment by tobiasbrunner** [comment]
> Changing usleep on kernel_pfroute_net.c lines 850 and 870 to 50000

That's the current value, or did you mean 500000?

Did you check if that IP address is actually there on the TUN device? (If you change the timeout, you'll have quite some time until the interface is deleted again.)

**Comment by UnauthorizedOne** [comment]
I have the same issue. This is from a fresh Monterey install in Parallels with the working configuration copied over from Big Sur:

> ...
IKE_SA myvpn[2] established between <...>
scheduling reauthentication in 9785s
maximum IKE_SA lifetime 10325s
installing <...> as DNS server
handling INTERNAL_IP4_NBNS attribute failed
installing <...> as DNS server
handling INTERNAL_IP4_NBNS attribute failed
installing new virtual IP <...>
created TUN device: utun3
virtual IP <...> did not appear on utun3
installing virtual IP <...> failed
selected proposal: ESP:AES_CBC_128/HMAC_SHA2_256_128/NO_EXT_SEQ
no acceptable traffic selectors found
failed to establish CHILD_SA, keeping IKE_SA
peer supports MOBIKE
sending DELETE for ESP CHILD_SA with SPI c7f38964
generating INFORMATIONAL request 2 [ D ]
sending packet: from <...>[4500] to <...>[4500] (80 bytes)
received packet: from <...>[4500] to <...>[4500] (80 bytes)
parsed INFORMATIONAL response 2 [ D ]
establishing connection 'myvpn' failed

I previously tried an upgrade installation from Big Sur to Monterey in another VM, lucky as I am, especially to try out strongswan, which my home office work strongly depends on. I can go back and forth between Big Sur and Monterey snapshots, the first one is working while the latter is not. I even tried a bare metal installation in a second APFS volume (restore from TimeMachine and upgrade to Monterey) with the same result.

**Comment by tobiasbrunner** [comment]
@UnauthorizedOne Did you check whether the IP address actually appears on the utun interface that's created?

**Comment by UnauthorizedOne** [comment]
@tobiasbrunner Will try that later today in a break. I suppose that can be checked using ifconfig during the enlarged timeout?

**Comment by UnauthorizedOne** [comment]
This is the verbose output if ifconfig for utun3 (from the fresh Monterey VM):
> utun3: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500 index 8
	eflags=1002080<TXSTART,NOAUTOIPV6LL,ECN_ENABLE>
	xflags=4<NOAUTONX>
	inet 192.168.2.2 --> 192.168.2.2 netmask 0xffffff00 
	state availability: 0 (true)
	scheduler: FQ_CODEL 
	qosmarking enabled: no mode: none
	low power mode: disabled
	multi layer packet logging (mpklog): disabled
	routermode4: disabled
	routermode6: disabled

**Comment by tobiasbrunner** [comment]
Thanks, that seems to be correct. So the question is why the address doesn't show up in our `getifaddrs()` call even with increased delays (i.e. those `usleep()` calls @tzahico changed). But actually, in your log output above there is no `interface utun3 appeared` message. Do you ever see that (maybe after increasing `vip_wait`)? Could you try increasing the time in the `usleep()` calls too (in particular the second one)? (Just to verify it really doesn't help.)

**Comment by UnauthorizedOne** [comment]
I never saw the `interface utun? appeared` message so far, also checked with increased `vip_wait` again. It is not generated on the working Big Sur setup as well:

>installing new virtual IP 192.168.2.2
created TUN device: utun6
selected proposal: ESP:AES_CBC_128/HMAC_SHA2_256_128/NO_EXT_SEQ
CHILD_SA myvpn{2} established with SPIs cb49a604_i ce87708e_o and TS 192.168.2.2/32 === 192.168.1.0/24 <...>
peer supports MOBIKE
connection 'myvpn' established successfully

I did not try to change any source file so far as I am using the bottle, although I tried to install the bottle from source once, but without luck. Would need some preparation for me to understand and setup the build environment.

_(In the upgrade installation I also tried with updated Xcode Command Line tools, which I noticed in the blog should be required in version 13.1 for Monterey, although `brew` seems to have no problems with previous versions and does not insist on updating, just `brew doctor` leaves a hint. However, that does not seem to be a problem in the fresh Monterey installation anyways.)_

**Comment by tobiasbrunner** [comment]
Hm, weird.  No idea how this could work without that message, or why it would not show up there (it's logged on level 1, like e.g. the `created TUN device` message). A log with the level for _knl_ increased to 2 might help (see #196 for log settings).

Since I don't have a device that can run macOS 12, I can't reproduce this. So it would be great if you could try to build from sources and increase the `usleep()` to see if that makes a difference (maybe to 1s = 1000000us or even more), and if it doesn't, maybe try other patches.

**Comment by tzahico** [comment]
Hi @tobiasbrunner - if you like, we can give you AnyDesk access to a macOS M1 device with Monterey.  We use this device for testing only, so feel free to do whatever you want with it :)  Let me know.

**Comment by tobiasbrunner** [comment]
That'd be great.

**Comment by tzahico** [comment]
Hi @tobiasbrunner  - I just sent an email with all details to the email listed at the bottom of https://www.strongswan.org/

Thanks,
Isaac

**Comment by tzahico** [comment]
Thank you, @tobiasbrunner !

**Comment by UnauthorizedOne** [comment]
Thanks from me as well, @tobiasbrunner. Will see, if I can find some time to build from source, or wait for the workaround or fix to appear in the Homebrew bottle.

**Comment by tobiasbrunner** [comment]
I had two other ideas. One is to set the MTU on the TUN device (the default of 1500 is too high anyway, in particular if _kernel-libipsec_ is used). That might trigger an `RTM_IFINFO` event without having to down the interface initially. I pushed this approach to the _707-macos-tun-mtu_ branch. It isn't tested, so I don't know if an event is actually triggered. Either way the patch probably makes sense.

Another approach would be to just trigger a manual query of the TUN device after creating it, or we could maybe even add the interface and address to our internal cache manually without waiting for any events (the creation of the device, "upping" it, and adding the address were seemingly successful at that point, so there is no reason why we shouldn't assume they are both available in the kernel). In either case we could probably get rid of the `usleep()` calls as it wouldn't matter if and when an `RTM_IFINFO` event is triggered, or whether there is an `RTM_NEWADDR` event (which hasn't been the case on macOS for a while, but might be e.g. on FreeBSD). And we could maybe even remove `vip_wait`, in the manual case anyway, but also when querying because while the lookup has to be done asynchronously, we could just wait for its result, so we don't need an arbitrary timeout to wait until events are processed that might or might not be generated by the kernel in the first place. I've not implemented this yet.

**Comment by tzahico** [comment]
Hi @tobiasbrunner  - we've tried https://github.com/strongswan/strongswan/commit/d1f0a334c42eb52d93d409db3d2a6335851284e0 but seems that we're now getting a new error:

failed to get interface flags for utun0: Bad file descriptor

`08[IKE] <mvpn.app-ikev2|1> installing new virtual IP 10.110.15.147
08[LIB] <mvpn.app-ikev2|1> failed to get interface flags for utun0: Bad file descriptor
08[IKE] <mvpn.app-ikev2|1> installing virtual IP 10.110.15.147 failed
08[CFG] <mvpn.app-ikev2|1> selected proposal: ESP:AES_CBC_128/HMAC_SHA1_96/NO_EXT_SEQ
08[IKE] <mvpn.app-ikev2|1> no acceptable traffic selectors found
08[IKE] <mvpn.app-ikev2|1> failed to establish CHILD_SA, keeping IKE_SA`

Please feel free to let me know if you need AnyDesk access.

Thanks,
Isaac

**Comment by tobiasbrunner** [comment]
Oh, I see. The socket for that is created only after the TUN device is created. Could you try the patch in the _707-macos-tun-mtu_ branch instead? I'd prefer that anyway if it fixes the issue.

**Comment by tzahico** [comment]
Hi @tobiasbrunner  - we tested the 707-macos-tun-mtu branch on Monterey (Intel) and it seems to be working well.  We'll test soon on M1 and let you know if there are any issues.

**Comment by tobiasbrunner** [comment]
OK, great. Thanks for testing.

I've pushed the fix to master. It should probably be included in the Homebrew build, I'll try to produce a patch for that.

**Comment by pieterwillaert** [comment]
Hi @tobiasbrunner, do you have any idea when this patch will be included in the homebrew build? 
regards

**Comment by tobiasbrunner** [comment]
No idea, but I doubt it will before the next release (they closed my issue).

**Comment by pieterwillaert** [comment]
Thx for the quick response, as a follow up: any idea when a new release can be expected?

**Comment by tobiasbrunner** [comment]
Please refer to [Milestones](https://github.com/strongswan/strongswan/milestones).

**Comment by pieterwillaert** [comment]
@tobiasbrunner I have created a PR for homebrew, but the tests are failing for the patch, 
https://github.com/Homebrew/homebrew-core/pull/89633

i'll try to look further into it tomorrow, but it would be great if you could help here

**Comment by tobiasbrunner** [comment]
Yeah, that's exactly why I didn't create a PR. Since the patch is not a commit, but applies to the tarball, it has to be stored somewhere. They have a repository with patches at [Homebrew/formula-patches](https://github.com/Homebrew/formula-patches), but I don't know if the idea is to create a PR there first and then one in Homebrew/homebrew-core, or if the patch should be stored in a Gist, or if what you did now (i.e. reference an issue attachment) would be OK, too. I haven't found a documentation on how this should be handled.

Why the file is detected as binary might be due to the extension (I attached it as `.txt` because GitHub for some reason does not allow attaching `.patch` files to issues).

**Comment by pieterwillaert** [comment]
Homebrew version is patched, just tested it and it works like a charm, thx for the assistance!

**Comment by UnauthorizedOne** [comment]
Confirmed, just tested version 5.9.4_1 with my clean VM that previously did not work with 5.9.4. Looking forward to upgrading to Monterey now, thanks so much! 👍
